import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node
import xacro

def generate_launch_description():
    pkg_path = get_package_share_directory('final_assemble_rover_description')
    
    # Locate the xacro file generated by Fusion 360
    xacro_file = os.path.join(pkg_path, 'urdf', 'final_assemble_rover.xacro')
    
    # Parse the xacro file into standard URDF XML
    robot_description_config = xacro.process_file(xacro_file)
    
    return LaunchDescription([
        Node(
            package='robot_state_publisher',
            executable='robot_state_publisher',
            parameters=[{'robot_description': robot_description_config.toxml()}]
        ),
        Node(
            package='joint_state_publisher_gui',
            executable='joint_state_publisher_gui'
        ),
        Node(
            package='rviz2',
            executable='rviz2'
        )
    ])